language: cpp
dist: trusty
matrix:
  include:
  - os: linux
    env: PYTHON=3.7
  - os: linux
    env: CONDA=3.7
  - os: osx
    env: PYTHON=3.7
  - os: osx
    env: CONDA=3.7
before_install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8 CC=gcc-4.8; fi
  if [ -n "$PYTHON" ]; then
    if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "${PYTHON:0:1}" = "3" ]; then
      brew update; brew install python3;
    fi
    pip install --user --upgrade pip virtualenv
    virtualenv -p python$PYTHON venv
    source venv/bin/activate
  elif [ -n "$CONDA" ]; then
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then OS=Linux-x86_64; else OS=MacOSX-x86_64; fi
    wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda${CONDA:0:1}-latest-$OS.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda config --set always_yes yes --set changeps1 no
    conda config --add channels conda-forge
    conda install -n base conda-devenv conda=4.6.14 conda-build
  fi
install:
- |
  conda devenv
  source activate cpp-bindings
  if [ -n "$PYTHON" ]; then
    python setup.py sdist
    pip install --verbose dist/*.tar.gz
  elif [ -n "$CONDA" ]; then
    conda build recipe
    conda install --use-local python_package
  fi
script:
- pytest .
