language: cpp
dist: trusty
matrix:
  include:
  - os: linux
    env: PYTHON=3.7
  - os: osx
    env: PYTHON=3.7
before_install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8 CC=gcc-4.8; fi
  if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "${PYTHON:0:1}" = "3" ]; then
    brew update; brew install python3;
  fi
#  pip install --user --upgrade pip virtualenv
#  virtualenv -p python$PYTHON venv
#  source venv/bin/activate
install:
- |
  conda devenv
  source activate cpp-bindings
  python setup.py sdist
  pip install --verbose dist/*.tar.gz
script:
- pytest .
