name: cpp-bindings
channels:
  - https://conda.anaconda.org/conda-forge/
dependencies:
  # All cpp stack dependencies
  - clangdev >=6.0
  - cmake
  - make

  # For the bindings
  - pybind11
  
  # Python requirements
  - python >=3.6.7
  - setuptools

  # For python tests
  - pytest
  - pytest-runner
