name: cpp-bindings
channels:
  - https://conda.anaconda.org/conda-forge/
dependencies:
  # All cpp stack dependencies
  - eigen 
  - clangdev >=6.0
  - cmake
  - make

  # For the bindings
  - pybind11
  
  # Additional python resources
  - notebook
  - ipython
  - ipywidgets 
  - widgetsnbextension 
  - jupyter_contrib_nbextensions 
  - python 
  - scipy 
  - numpy 
  - pandas

environment:
  PYTHONPATH:
    - {{ root }}/artifacts
