jobs:
- job:
  displayName: 'Windows 2019'

  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: |
      conda config --system --set always_yes yes --set changeps1 no
      conda config --system --append channels conda-forge
      conda install -n base conda-devenv conda=4.6.14
    displayName: 'Configuring conda'

  - script: |
      conda info -a
      conda devenv
    displayName: 'Running conda devenv'

  - script: |
      call activate cpp-bindings
      python3 setup.py install
      python3 setup.py test
    displayName: 'Installation and tests'
